### ISSUE TITLE
Databricks secret scope configuration

### ISSUE THREAD

**Issue by nansravn** [microsoft/devsquad-in-a-day#11]
- Improve the documentation regarding databricks secret scope configuration (system env variable configuration and databricks configure --token).

**Comment by fabiohaifa** [comment]
I've change the pipeline sequence of IaC CD to deploy part of the DatabricsSecrets into a new task on the deploy's sequence.

That is a part os scope secrets that need to run with Azure AD User that doesn't apply to the pipe (it run with SP credencials). So I've change the documentation with a simple version of this script execution until Microsoft release a fix regarding this situation:

https://docs.microsoft.com/en-us/azure/databricks/security/secrets/secret-scopes#create-an-azure-key-vault-backed-secret-scope-using-the-databricks-cli

![image](https://user-images.githubusercontent.com/61516935/153479108-4df31428-5122-4f17-a185-ceaa44674009.png)
