### ISSUE TITLE
[BUG] - Broken link on quickstart documentation

### ISSUE THREAD

**Issue by cezapata** [microsoft/devsquad-in-a-day#59]
**Describe the bug**
On the last part of [Step 2](https://github.com/microsoft/devsquad-in-a-day/tree/main/quickstart#step-2-setup-the-hands-on-lab-configuration-file) for the lab, there is a broken link under the following text:
```markdown
(OPTIONAL) If you are using this project as a Hands-On Lab, feel free to proceed to the next step of the lab setup. If you are using this project as a template for dataops, check [this additional documentation](https://github.com/microsoft/devsquad-in-a-day/blob/main/quickstart/1b-create-prereqs-azure-advanced.md) that explains advanced configuration options.
```

It looks like this link may have been broken since this line was introduced, according to the following commit:

https://github.com/microsoft/devsquad-in-a-day/commit/d871af8410ed26c952d7b10e19d8f0f3af84936c

**To Reproduce**
Go through the quickstart setup instructions
1. At the end of step two, click on the link for checking additional documentation.

**Expected behavior**
The link should send you to a place where you can get advanced configuration options

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: All OS
 - Browser: All browsers
 - Version All versions

**Additional context**
N/A

**Comment by fabiohaifa** [comment]
Adjusted on last commit;
